repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: old_ARTIBOT.py|Last_working_bot_but_one_py
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: old_ARTIBOT.py|Last_working_bot_but_one_py
