name: Smoke Test

on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Lint and test
        run: |
          ruff check .
          black . --check
          pytest -q
